name: Container Scan Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  container-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t demo-image .

      - name: Run Snyk Container Scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: demo-image
          args: --severity-threshold=medium
